@extends('layouts.app')
@section('content')
<section class="page-head detail-head">
    <div><a class="back-link" href="{{ route('leads.index') }}">&larr; All leads</a><h1>{{ $lead->full_name }}</h1><p class="subhead">{{ $lead->company_name ?: 'Independent lead' }} &middot; {{ $lead->city ?: 'Location not set' }}</p></div>
    <div class="head-actions"><a class="button button-quiet" href="{{ route('leads.edit',$lead) }}">Edit lead</a><form method="POST" action="{{ route('leads.destroy',$lead) }}">@csrf @method('DELETE')<button class="button button-danger" onclick="return confirm('Delete this lead?')">Delete</button></form></div>
</section>
<section class="detail-grid">
    <div>
        <div class="profile-card"><div class="profile-top"><span class="avatar avatar-large">{{ substr($lead->full_name,0,1) }}</span><div><span class="status status-{{ strtolower(str_replace('-','',$lead->status)) }}">{{ $lead->status }}</span><h2>{{ $lead->mobile_number }}</h2><a class="whatsapp" target="_blank" href="https://wa.me/{{ preg_replace('/\D/','',$lead->mobile_number) }}?text={{ urlencode('Hi '.$lead->full_name.', following up on our conversation.') }}">&#9673; Message on WhatsApp</a></div></div><div class="profile-facts"><div><small>Email</small><span>{{ $lead->email ?: 'Not provided' }}</span></div><div><small>Source</small><span>{{ $lead->source?->name ?? 'Other' }}</span></div><div><small>Service</small><span>{{ $lead->service?->name ?? 'Not set' }}</span></div><div><small>Next follow-up</small><span>{{ $lead->next_followup_at?->format('d M Y, H:i') ?? 'Not scheduled' }}</span></div></div></div>
        <div class="panel timeline-panel"><div class="panel-head"><div><p class="eyebrow">Conversation log</p><h2>Follow-up timeline</h2></div></div>@forelse($lead->followups as $followup)<div class="timeline-item"><span class="timeline-dot"></span><div><div class="timeline-meta"><strong>{{ $followup->type }}</strong><span>{{ $followup->followup_at->format('d M Y &middot; H:i') }}</span></div><p>{{ $followup->note }}</p>@if($followup->next_followup_at)<small>Next: {{ $followup->next_followup_at->format('d M Y, H:i') }}</small>@endif @if($followup->attachment)<p><a class="text-link" target="_blank" href="{{ route('leads.followups.attachment', [$lead, $followup]) }}">{{ $followup->attachment->type === 'photo' ? 'View photo' : 'Open document' }}: {{ $followup->attachment->original_name }}</a></p>@endif</div></div>@empty<p class="empty">No follow-ups yet. Log the first touchpoint below.</p>@endforelse</div>
    </div>
    <div class="panel followup-panel"><p class="eyebrow">Log activity</p><h2>New follow-up</h2><form method="POST" enctype="multipart/form-data" action="{{ route('leads.followup',$lead) }}">@csrf<label>Date & time<input type="datetime-local" name="followup_at" value="{{ now()->format('Y-m-d\TH:i') }}" required></label><label>Type<select name="type"><option>Call</option><option>WhatsApp</option><option>Meeting</option><option>Email</option></select></label><label>Note / message<textarea name="note" placeholder="What happened?" required></textarea></label><label>Next follow-up<input type="datetime-local" name="next_followup_at"></label><label>Status after follow-up<select name="status_after">@foreach(['New','Contacted','Interested','Follow-up','Converted','Lost'] as $status)<option @selected($lead->status===$status)>{{ $status }}</option>@endforeach</select></label><label>Photo or document<input type="file" name="attachment" accept="image/jpeg,image/png,image/webp,.pdf,.doc,.docx,.xls,.xlsx"><small class="mono">Optional. One file, up to 10 MB.</small></label><button class="button button-primary full" type="submit">Save follow-up <span>-></span></button></form></div>
</section>
@endsection
